# Generated by Django 2.1.5 on 2021-01-27 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
